# This is a docker-compose file for a Next.js application with MongoDB
networks:
  portfolio-net:
    driver: bridge

services:
  # Define the Vite.js application
  portfolio-app:
    hostname: az-portfolio
    # depends_on:
    #   - database
    container_name: az-portfolio
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: unless-stopped
    ports:
      - "4173:4173"
  # Define the MongoDB service
  mongo-db:
    hostname: portfolio-mongo-db
    container_name: portfolio-mongo-db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
      # Create a new database. Please note, the
      # /docker-entrypoint-initdb.d/init.js has to be executed
      # in order for the database to be created
      MONGO_INITDB_DATABASE: users
    volumes:
      # Add the db-init.js file to the Mongo DB container
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "4174:27017"
  clips-app:
    hostname: az-portfolio-clips
    container_name: az-portfolio-clips
    image: avshalomts/clips:latest
    restart: unless-stopped
    ports:
      - "4175:4200"
# docker-compose build --no-cache
# docker-compose up -d --build
