/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\angular-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/angular-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logo.geometry} material={materials['Material.001']} scale={1.901} />
    </group>
  )
}

useGLTF.preload('/models/angular-logo.glb')
