/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\angular-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes } = useGLTF('/models/angular-logo.glb')

  const meshMaterial = new THREE.MeshStandardMaterial({
      color: "white",
    });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logo.geometry} material={meshMaterial} scale={1.901} />
    </group>
  )
}

useGLTF.preload('/models/angular-logo.glb')
