/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\aws-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/aws-logo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-13.076, 155.698, -20.264]} scale={[16067.461, 16067.46, 16067.46]}>
          <mesh geometry={nodes.ArrowBody_Material001_0.geometry} material={materials['Material.001']} position={[-0.003, -0.021, 0]} />
        </group>
        <group position={[593.304, 205.677, -20.264]} scale={[16067.461, 16067.46, 16067.46]}>
          <mesh geometry={nodes.ArrowHead_Material001_0.geometry} material={materials['Material.001']} position={[-0.003, -0.021, 0]} />
        </group>
        <group position={[41.538, 612.01, -20.264]} scale={[16067.461, 16067.46, 16067.46]}>
          <mesh geometry={nodes.AWS_Material003_0.geometry} material={materials['Material.003']} position={[-0.003, -0.021, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/aws-logo.glb')
