/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\css-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/css-logo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[136.111, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane001__0_1.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Plane001__0_2.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/css-logo.glb')
