/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\github-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/github-logo.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.055, 2.945, 6.336]} rotation={[Math.PI / 2, 0, 0]} scale={28.364}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.glossy_putih} position={[0.002, -0.223, 0.104]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/github-logo.glb')
