/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\linux-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/linux-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Tux-printable_1'].geometry} material={materials.black} />
      <mesh geometry={nodes['Tux-printable_2'].geometry} material={materials.white} />
      <mesh geometry={nodes['Tux-printable_3'].geometry} material={materials.orange} />
    </group>
  )
}

useGLTF.preload('/models/linux-logo.glb')
