/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\microsoft-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/microsoft-logo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-1144.092, 42.351, -454.462]} scale={100}>
          <mesh geometry={nodes.WindowsLogo2_2_WindowsLogo2_2_0.geometry} material={materials.WindowsLogo5_2_2} />
          <mesh geometry={nodes.WindowsLogo2_2_WindowsLogo2_2_2_0.geometry} material={materials.WindowsLogo2_2_2} />
          <mesh geometry={nodes.WindowsLogo2_2_WindowsLogo2_2_3_0.geometry} material={materials.WindowsLogo5_2_4} />
          <mesh geometry={nodes.WindowsLogo2_2_WindowsLogo2_2_4_0.geometry} material={materials.WindowsLogo4_2_4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/microsoft-logo.glb')
